/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2013 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package ti.modules.titanium.charts;

import org.appcelerator.kroll.KrollModule;
import org.appcelerator.kroll.annotations.Kroll;

import org.appcelerator.titanium.TiApplication;
import org.appcelerator.titanium.TiC;
import org.appcelerator.titanium.view.TiAnimation;
import org.appcelerator.kroll.common.Log;

import android.graphics.Matrix;
import android.graphics.Paint.Align;

@Kroll.module
public class ChartsModule extends KrollModule
{
	public static float[] gradientCoordsFromAngle(int width, int height, int angle) {
		float[] result = {0, height/2, width, height/2};
		Matrix matrix = new Matrix();
		matrix.setRotate(-angle, width/2, height/2);
		matrix.mapPoints(result);
	    Log.d(TAG, "gradientCoordsFromAngle " + result[0] + ", " + result[1] + ", " + result[2] + ", " + result[3], Log.DEBUG_MODE);
		return result;
	}
	// Standard Debugging variables
	private static final String TAG = "ChartsModule";
	@Kroll.constant public static final int ALIGNMENT_LEFT = 0;
	@Kroll.constant public static final int ALIGNMENT_CENTER = 1;
	@Kroll.constant public static final int ALIGNMENT_RIGHT = 2;
	@Kroll.constant public static final int ALIGNMENT_TOP = 3;
	@Kroll.constant public static final int ALIGNMENT_MIDDLE = 4;
	@Kroll.constant public static final int ALIGNMENT_BOTTOM = 5;
	@Kroll.constant public static final int LOCATION_TOP = 0;
	@Kroll.constant public static final int LOCATION_BOTTOM = 7;
	@Kroll.constant public static final int LOCATION_LEFT = 2;
	@Kroll.constant public static final int LOCATION_RIGHT = 5;
	@Kroll.constant public static final int CAP_BUTT = 0;
	@Kroll.constant public static final int CAP_ROUND = 1;
	@Kroll.constant public static final int CAP_SQUARE = 2;
	@Kroll.constant public static final int JOIN_MITER = 0;
	@Kroll.constant public static final int JOIN_ROUND = 1;
	@Kroll.constant public static final int JOIN_BEVEL = 2;
	@Kroll.constant public static final int BAR_WIDTH_FIXED = 0;
	@Kroll.constant public static final int BAR_WIDTH_VARIABLE = 1;
	@Kroll.constant public static final int BAR_STYLE_OVERLAID = 0;
	@Kroll.constant public static final int BAR_STYLE_STACKED = 1;
	@Kroll.constant public static final int BAR_STYLE_SIDE_BY_SIDE = 2;
	@Kroll.constant public static final int HORIZONTAL = 0;
	@Kroll.constant public static final int VERTICAL = 1;
//	@Kroll.constant public static final int STYLE_DIAMOND = PointStyle.DIAMOND;
//	@Kroll.constant public static final int STYLE_CIRCLE = PointStyle.CIRCLE;
//	@Kroll.constant public static final int STYLE_POINT = PointStyle.POINT;
//	@Kroll.constant public static final int STYLE_SQUARE = PointStyle.SQUARE;
//	@Kroll.constant public static final int STYLE_TRIANGLE = PointStyle.TRIANGLE;
	
	public ChartsModule()
	{
		super();
	}

	@Kroll.onAppCreate
	public static void onAppCreate(TiApplication app)
	{
		Log.d(TAG, "inside onAppCreate");
		// put module init code that needs to run when the application is created
	}
}

