/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by 
 * Appcelerator. It should not be modified by hand.
 */
package com.titanium.test;

import java.lang.reflect.Method;
import java.util.HashMap;
import java.util.Iterator;
import java.util.Map;

import org.appcelerator.kroll.common.TiConfig;
import org.appcelerator.kroll.runtime.v8.V8Runtime;
import org.appcelerator.kroll.KrollExternalModule;
import org.appcelerator.kroll.KrollModule;
import org.appcelerator.kroll.KrollModuleInfo;
import org.appcelerator.kroll.KrollRuntime;
import org.appcelerator.titanium.TiApplication;
import org.appcelerator.titanium.TiRootActivity;
import akylas.shapes.*;
import akylas.commonjs.*;
import akylas.slidemenu.*;
import akylas.millenoki.vpn.*;


public final class TitaniumtestApplication extends TiApplication
{
	private static final String TAG = "TitaniumtestApplication";

	@SuppressWarnings("static-access")
	@Override
	public void onCreate()
	{
		super.onCreate();

		appInfo = new TitaniumtestAppInfo(this);
		postAppInfo();
		
		HashMap<String,Class[]> modules = new HashMap<String, Class[]>() {
		     {
			      put("akylas.shapes", new Class[]{akylas.shapes.AkylasShapesBootstrap.class, akylas.shapes.AkylasShapesModule.class});
			      put("akylas.commonjs", new Class[]{akylas.commonjs.AkylasCommonjsBootstrap.class, akylas.commonjs.AkylasCommonjsModule.class});
			      put("akylas.slidemenu", new Class[]{akylas.slidemenu.AkylasSlidemenuBootstrap.class, akylas.slidemenu.AkylasSlidemenuModule.class});
			      put("akylas.mapbox", new Class[]{akylas.mapbox.AkylasMapboxBootstrap.class, akylas.mapbox.AkylasMapboxModule.class});
			      put("akylas.millenoki.vpn", new Class[]{akylas.millenoki.vpn.MillenokiVpnBootstrap.class, akylas.millenoki.vpn.MillenokiVpnModule.class});
		     }
		 };

		V8Runtime runtime = new V8Runtime();
		Iterator it = modules.entrySet().iterator();
	    while (it.hasNext()) {
	        Map.Entry pairs = (Map.Entry)it.next();
	        runtime.addExternalModule((String) pairs.getKey(),
					(Class<? extends KrollExternalModule>) (((Class[])(pairs.getValue()))[0]));
	    }
		runtime.addExternalCommonJsModule("akylas.commonjs", akylas.commonjs.CommonJsSourceProvider.class);

		

		KrollRuntime.init(this, runtime);
		

		// stylesheet = new ApplicationStylesheet();
		postOnCreate();
		TiConfig.DEBUG = TiConfig.LOGD = true;

		// Custom modules
		KrollModuleInfo moduleInfo;

		try {
			it = modules.entrySet().iterator();
		    while (it.hasNext()) {
		        Map.Entry pairs = (Map.Entry)it.next();
		        
		        Method method = ((((Class[])(pairs.getValue()))[1])).getMethod("onAppCreate", TiApplication.class);
		        method.invoke(null,this);
		        moduleInfo = new KrollModuleInfo((String) pairs.getKey(),(String) pairs.getKey(), "","", "", "","", "");
				KrollModule.addCustomModuleInfo(moduleInfo);
		    }
		} catch (Exception e) {
		}
	}

	@Override
	public void verifyCustomModules(TiRootActivity rootActivity)
	{
	}
}
