//
//  TiUISlideMenuOptionsProxy.m
//  Titanium
//
//  Created by Martin Guillon on 11/10/13.
//
//

#ifdef USE_TI_UISLIDEMENUOPTIONS
#import "TiUISlideMenuOptionsProxy.h"
#import "SlideMenuDrawerController.h"

@implementation TiUISlideMenuOptionsProxy


MAKE_SYSTEM_PROP(PANNING_NONE, MMOpenDrawerGestureModeNone);
MAKE_SYSTEM_PROP(PANNING_ALL_VIEWS, MMOpenDrawerGestureModeAll);
MAKE_SYSTEM_PROP(PANNING_CENTER_VIEW, MMOpenDrawerGestureModePanningCenterView);
MAKE_SYSTEM_PROP(PANNING_BORDERS, MMOpenDrawerGestureModeBezelPanningCenterView);
MAKE_SYSTEM_PROP(PANNING_NAVBAR, MMOpenDrawerGestureModePanningNavigationBar);


MAKE_SYSTEM_PROP(ANIMATION_NONE, 0);
MAKE_SYSTEM_PROP(ANIMATION_ZOOM, 1);
MAKE_SYSTEM_PROP(ANIMATION_SCALE, 2);
MAKE_SYSTEM_PROP(ANIMATION_SLIDE, 3);


MAKE_SYSTEM_PROP(PROPERTY_ANIMATION_LEFT, @"animationLeft");
MAKE_SYSTEM_PROP(PROPERTY_ANIMATION_RIGHT, @"animationRight");
MAKE_SYSTEM_PROP(PROPERTY_LEFT_VIEW, @"leftView");
MAKE_SYSTEM_PROP(PROPERTY_LEFT_VIEW_DISPLACEMENT, @"leftViewDisplacement");
MAKE_SYSTEM_PROP(PROPERTY_LEFT_VIEW_WIDTH, @"leftViewWidth");
MAKE_SYSTEM_PROP(PROPERTY_RIGHT_VIEW, @"rightView");
MAKE_SYSTEM_PROP(PROPERTY_RIGHT_VIEW_DISPLACEMENT, @"rightViewDisplacement");
MAKE_SYSTEM_PROP(PROPERTY_RIGHT_VIEW_WIDTH, @"rightViewWidth");
MAKE_SYSTEM_PROP(PROPERTY_PANNING_MODE, @"panningMode");
MAKE_SYSTEM_PROP(PROPERTY_CENTER_VIEW, @"centerView");
MAKE_SYSTEM_PROP(PROPERTY_FADING, @"fading");
@end
#endif